apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp
spec:
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
      - name: studentapp
        image: surajbele/devop-b5:student
        ports:
        - containerPort: 8080
